/* eslint-disable import/prefer-default-export,camelcase */
// hand:
// easy to write by hand with this
// automation:
// but may not be easy to translate automation
// please archive each language to it's own file when automation
// export const en = ``
// export const zh = ``

/**
 * ot language at: the 1th, 3th, 5th
 * en language at: the 0th, 2th, 4th
 * @sample
 * ```
 * let map=`
 * en line
 * zh line
 * `
 * ```
 */
export const en_zh_map = `
 feat|fix|docs|style|refactor|preform|test|tool(chore)|revert
 新增|修复|文档|格式|重构|性能|测试|工具|回滚
 change all thing|generated by ymc@robot
 更改所有类型|由 ymc@robot 自动生成
 `
